/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/accounts': RouteRecordInfo<'/accounts', '/accounts', Record<never, never>, Record<never, never>, '/accounts/login' | '/accounts/logoff' | '/accounts/logon' | '/accounts/logout'>,
    '/accounts/login': RouteRecordInfo<'/accounts/login', '/accounts/login', Record<never, never>, Record<never, never>>,
    '/accounts/logoff': RouteRecordInfo<'/accounts/logoff', '/accounts/logoff', Record<never, never>, Record<never, never>>,
    '/accounts/logon': RouteRecordInfo<'/accounts/logon', '/accounts/logon', Record<never, never>, Record<never, never>>,
    '/accounts/logout': RouteRecordInfo<'/accounts/logout', '/accounts/logout', Record<never, never>, Record<never, never>>,
    '/contents': RouteRecordInfo<'/contents', '/contents', Record<never, never>, Record<never, never>, '/contents/' | '/contents/destinations' | '/contents/tokens' | '/contents/users'>,
    '/contents/': RouteRecordInfo<'/contents/', '/contents', Record<never, never>, Record<never, never>>,
    '/contents/destinations': RouteRecordInfo<'/contents/destinations', '/contents/destinations', Record<never, never>, Record<never, never>>,
    '/contents/tokens': RouteRecordInfo<'/contents/tokens', '/contents/tokens', Record<never, never>, Record<never, never>>,
    '/contents/users': RouteRecordInfo<'/contents/users', '/contents/users', Record<never, never>, Record<never, never>>,
    '/examples': RouteRecordInfo<'/examples', '/examples', Record<never, never>, Record<never, never>, '/examples/' | '/examples/plugins' | '/examples/plugins/dialog' | '/examples/plugins/locales' | '/examples/plugins/moment' | '/examples/plugins/storeGet' | '/examples/plugins/storeSet' | '/examples/wireframes' | '/examples/wireframes/baseline' | '/examples/wireframes/constrained' | '/examples/wireframes/discord' | '/examples/wireframes/extended-toolbar' | '/examples/wireframes/inbox' | '/examples/wireframes/side-navigation' | '/examples/wireframes/steam' | '/examples/wireframes/system-bar' | '/examples/wireframes/three-column'>,
    '/examples/': RouteRecordInfo<'/examples/', '/examples', Record<never, never>, Record<never, never>>,
    '/examples/plugins': RouteRecordInfo<'/examples/plugins', '/examples/plugins', Record<never, never>, Record<never, never>, '/examples/plugins/dialog' | '/examples/plugins/locales' | '/examples/plugins/moment' | '/examples/plugins/storeGet' | '/examples/plugins/storeSet'>,
    '/examples/plugins/dialog': RouteRecordInfo<'/examples/plugins/dialog', '/examples/plugins/dialog', Record<never, never>, Record<never, never>>,
    '/examples/plugins/locales': RouteRecordInfo<'/examples/plugins/locales', '/examples/plugins/locales', Record<never, never>, Record<never, never>>,
    '/examples/plugins/moment': RouteRecordInfo<'/examples/plugins/moment', '/examples/plugins/moment', Record<never, never>, Record<never, never>>,
    '/examples/plugins/storeGet': RouteRecordInfo<'/examples/plugins/storeGet', '/examples/plugins/storeGet', Record<never, never>, Record<never, never>>,
    '/examples/plugins/storeSet': RouteRecordInfo<'/examples/plugins/storeSet', '/examples/plugins/storeSet', Record<never, never>, Record<never, never>>,
    '/examples/wireframes': RouteRecordInfo<'/examples/wireframes', '/examples/wireframes', Record<never, never>, Record<never, never>, '/examples/wireframes/baseline' | '/examples/wireframes/constrained' | '/examples/wireframes/discord' | '/examples/wireframes/extended-toolbar' | '/examples/wireframes/inbox' | '/examples/wireframes/side-navigation' | '/examples/wireframes/steam' | '/examples/wireframes/system-bar' | '/examples/wireframes/three-column'>,
    '/examples/wireframes/baseline': RouteRecordInfo<'/examples/wireframes/baseline', '/examples/wireframes/baseline', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/constrained': RouteRecordInfo<'/examples/wireframes/constrained', '/examples/wireframes/constrained', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/discord': RouteRecordInfo<'/examples/wireframes/discord', '/examples/wireframes/discord', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/extended-toolbar': RouteRecordInfo<'/examples/wireframes/extended-toolbar', '/examples/wireframes/extended-toolbar', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/inbox': RouteRecordInfo<'/examples/wireframes/inbox', '/examples/wireframes/inbox', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/side-navigation': RouteRecordInfo<'/examples/wireframes/side-navigation', '/examples/wireframes/side-navigation', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/steam': RouteRecordInfo<'/examples/wireframes/steam', '/examples/wireframes/steam', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/system-bar': RouteRecordInfo<'/examples/wireframes/system-bar', '/examples/wireframes/system-bar', Record<never, never>, Record<never, never>>,
    '/examples/wireframes/three-column': RouteRecordInfo<'/examples/wireframes/three-column', '/examples/wireframes/three-column', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/accounts.vue': {
      routes: '/accounts' | '/accounts/login' | '/accounts/logoff' | '/accounts/logon' | '/accounts/logout'
      views: 'default'
    }
    'src/pages/accounts/login.vue': {
      routes: '/accounts/login'
      views: never
    }
    'src/pages/accounts/logoff.vue': {
      routes: '/accounts/logoff'
      views: never
    }
    'src/pages/accounts/logon.vue': {
      routes: '/accounts/logon'
      views: never
    }
    'src/pages/accounts/logout.vue': {
      routes: '/accounts/logout'
      views: never
    }
    'src/pages/contents.vue': {
      routes: '/contents' | '/contents/' | '/contents/destinations' | '/contents/tokens' | '/contents/users'
      views: 'default'
    }
    'src/pages/contents/index.vue': {
      routes: '/contents/'
      views: never
    }
    'src/pages/contents/destinations.vue': {
      routes: '/contents/destinations'
      views: never
    }
    'src/pages/contents/tokens.vue': {
      routes: '/contents/tokens'
      views: never
    }
    'src/pages/contents/users.vue': {
      routes: '/contents/users'
      views: never
    }
    'src/pages/examples.vue': {
      routes: '/examples' | '/examples/' | '/examples/wireframes/baseline' | '/examples/wireframes/constrained' | '/examples/plugins/dialog' | '/examples/wireframes/discord' | '/examples/wireframes/extended-toolbar' | '/examples/wireframes/inbox' | '/examples/plugins/locales' | '/examples/plugins/moment' | '/examples/plugins' | '/examples/wireframes/side-navigation' | '/examples/wireframes/steam' | '/examples/plugins/storeGet' | '/examples/plugins/storeSet' | '/examples/wireframes/system-bar' | '/examples/wireframes/three-column' | '/examples/wireframes'
      views: 'default'
    }
    'src/pages/examples/index.vue': {
      routes: '/examples/'
      views: never
    }
    'src/pages/examples/plugins.vue': {
      routes: '/examples/plugins' | '/examples/plugins/dialog' | '/examples/plugins/locales' | '/examples/plugins/moment' | '/examples/plugins/storeGet' | '/examples/plugins/storeSet'
      views: 'default'
    }
    'src/pages/examples/plugins/dialog.vue': {
      routes: '/examples/plugins/dialog'
      views: never
    }
    'src/pages/examples/plugins/locales.vue': {
      routes: '/examples/plugins/locales'
      views: never
    }
    'src/pages/examples/plugins/moment.vue': {
      routes: '/examples/plugins/moment'
      views: never
    }
    'src/pages/examples/plugins/storeGet.vue': {
      routes: '/examples/plugins/storeGet'
      views: never
    }
    'src/pages/examples/plugins/storeSet.vue': {
      routes: '/examples/plugins/storeSet'
      views: never
    }
    'src/pages/examples/wireframes.vue': {
      routes: '/examples/wireframes' | '/examples/wireframes/baseline' | '/examples/wireframes/constrained' | '/examples/wireframes/discord' | '/examples/wireframes/extended-toolbar' | '/examples/wireframes/inbox' | '/examples/wireframes/side-navigation' | '/examples/wireframes/steam' | '/examples/wireframes/system-bar' | '/examples/wireframes/three-column'
      views: 'default'
    }
    'src/pages/examples/wireframes/baseline.vue': {
      routes: '/examples/wireframes/baseline'
      views: never
    }
    'src/pages/examples/wireframes/constrained.vue': {
      routes: '/examples/wireframes/constrained'
      views: never
    }
    'src/pages/examples/wireframes/discord.vue': {
      routes: '/examples/wireframes/discord'
      views: never
    }
    'src/pages/examples/wireframes/extended-toolbar.vue': {
      routes: '/examples/wireframes/extended-toolbar'
      views: never
    }
    'src/pages/examples/wireframes/inbox.vue': {
      routes: '/examples/wireframes/inbox'
      views: never
    }
    'src/pages/examples/wireframes/side-navigation.vue': {
      routes: '/examples/wireframes/side-navigation'
      views: never
    }
    'src/pages/examples/wireframes/steam.vue': {
      routes: '/examples/wireframes/steam'
      views: never
    }
    'src/pages/examples/wireframes/system-bar.vue': {
      routes: '/examples/wireframes/system-bar'
      views: never
    }
    'src/pages/examples/wireframes/three-column.vue': {
      routes: '/examples/wireframes/three-column'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
